version: '4.5'

services:
  templates:
    build: .
    ports:
      - "50051:50051"
  
  templates-postgres:
    image: postgres:13.14-alpine3.19
    restart: always
    volumes:
      - template-pgdata:/var/lib/postgresql/data
    env_file:
      - .env.pg
    environment:
      - PSQL_URL='postgresql://postgres:postgres@localhost:5432/fichi'
    ports:
      - "5437:5432"
volumes:
  templates-pgdata: